### ISSUE TITLE
怎么设置qq:cookie

### ISSUE THREAD

**Issue by rouvaednE** [UnblockNeteaseMusic/server-rust#133]
按照文档所说查了documen.cookie，但是只有uin，没有 qm_keyst的值

**Comment by pan93412** [comment]
h! @1715173329

**Comment by rouvaednE** [comment]
> h! @1715173329

解决了 原来的网页端已经登陆过了 所以没有了 重新登陆之后就查到了

**Comment by pan93412** [comment]
46d5e15a09eed3e6de6b181ae116f0d1bc6e60a1 有加入相關的設定指引了
