### ISSUE TITLE
歌曲匹配错误

### ISSUE THREAD

**Issue by Heporis** [UnblockNeteaseMusic/server-rust#157]
用ypm时，好多歌曲匹配的都不对，不知道怎么办，指定特定的源是不是会起作用？不知道这个匹配机制是什么，但是网易云音乐上有的歌曲时长和别的曲库是有几秒的差别的，感觉不能只看时长。在别的曲库搜的第一个结果往往就是正确的，但是匹配出来的就是错的。关于匹配时间过长的问题，是不是可以预读播放列表，预先查询匹配？@pan93412

**Comment by Heporis** [comment]
> 實際上這應該是 server-rust 的問題⋯⋯已經 transferred 了。

这个问题解决了吗？想听的歌听不到，被搞得都没心情听歌了，好久没打开ypm了

**Comment by pan93412** [comment]
> > 實際上這應該是 server-rust 的問題⋯⋯已經 transferred 了。
> 
> 这个问题解决了吗？想听的歌听不到，被搞得都没心情听歌了，好久没打开ypm了

由於這個專案還是比較偏學習、實驗性質的，如果真的很喜歡這首歌的話，從正版的音樂平台購買專輯，或訂閱串流音樂平台，比較可以支持歌曲原作者喔。

**Comment by pan93412** [comment]
Related: #103
