### ISSUE TITLE
unm-resolver: 完成 migu engine

### ISSUE THREAD

**Issue by pan93412** [UnblockNeteaseMusic/server-rust#57]

**Comment by memorydream** [comment]
我今天下午在尝试做这个

咪咕确实不需要cookie，我没有使用cookie但是从search接口拿到了数据

**Comment by 1715173329** [comment]
> 我今天下午在尝试做这个
> 
> 目前来看咪咕确实不需要cookie，我没有使用cookie但是从search接口拿到了数据

不传递 cookie 仅能获取 128 Kbps 音源。

**Comment by memorydream** [comment]
> 

OK，我之后把cookie增加上，但是我没有cookie不能测试

**Comment by memorydream** [comment]
> > 我今天下午在尝试做这个
> > 目前来看咪咕确实不需要cookie，我没有使用cookie但是从search接口拿到了数据
> 
> 不传递 cookie 仅能获取 128 Kbps 音源。

OK，我之后把cookie增加上，但是我没有cookie不能测试
